# Generated by Django 5.0.6 on 2024-06-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tab_td',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True, null=True)),
                ('placa', models.CharField(blank=True, max_length=8, null=True)),
                ('motorista', models.CharField(blank=True, max_length=30, null=True)),
                ('ajudante', models.CharField(blank=True, max_length=30, null=True)),
                ('td', models.IntegerField(blank=True, null=True)),
                ('km', models.IntegerField(blank=True, default=0, null=True)),
                ('cliente', models.CharField(blank=True, max_length=30, null=True)),
                ('nota_1', models.IntegerField(blank=True, default=0, null=True)),
                ('nota_2', models.IntegerField(blank=True, default=0, null=True)),
                ('p2', models.IntegerField(blank=True, default=0, null=True)),
                ('p5', models.IntegerField(blank=True, default=0, null=True)),
                ('p8', models.IntegerField(blank=True, default=0, null=True)),
                ('p13', models.IntegerField(blank=True, default=0, null=True)),
                ('p20', models.IntegerField(blank=True, default=0, null=True)),
                ('p45', models.IntegerField(blank=True, default=0, null=True)),
                ('entrada', models.TimeField(blank=True, null=True)),
                ('saida', models.TimeField(blank=True, null=True)),
                ('OBS', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
